"""Markdown report emitter (cross-cutting §7). Deterministic render of the
normalized finding set — no LLM."""
from __future__ import annotations

from pr_review.extract.schema import DeltaManifest
from pr_review.findings.schema import NormalizedFindingSet
from pr_review.schema import Finding, Severity

_SEV_BADGE = {
    Severity.CRITICAL: "🟥 CRITICAL",
    Severity.HIGH: "🟧 HIGH",
    Severity.MEDIUM: "🟨 MEDIUM",
    Severity.LOW: "⬜ LOW",
    Severity.INFO: "ℹ️ INFO",
}


def _fence_safe(text: str) -> str:
    """Stop a snippet from closing the code fence it is rendered inside.

    Evidence is stored verbatim (cross-cutting §1) and rendered inside a ```
    block. A snippet containing its own fence ends that block early, and
    everything after it renders as markdown — so crafted evidence could inject
    headings, links or an image into a report that gets posted as a PR comment.
    The same shape of hole `safety/wrap.py` closes for prompts, on the output
    side. Only the rendering is defanged; the stored finding is untouched.

    Defanged with visible spaces rather than a zero-width joiner: an invisible
    character is what `sentinel.py`'s `hidden-text` rule exists to report, and
    emitting one from the reporter would be absurd.
    """
    return text.replace("```", "` ` `")


def _finding_block(f: Finding) -> str:
    ev = f.evidence[0] if f.evidence else None
    cwe = ", ".join(f.taxonomy.cwe) or "—"
    lines = [
        f"### {_SEV_BADGE[f.severity]} — {f.title}",
        "",
        f"- **Location:** `{f.location.file}:{f.location.start_line}`",
        f"- **Taxonomy:** {f.taxonomy.family} · OWASP {f.taxonomy.owasp_2025} · {cwe}",
        f"- **Confidence:** {f.confidence}/10 · **Status:** {f.status.value} · "
        f"**Detector:** {f.provenance.tool}",
    ]
    if ev:
        lines += ["", "```", f"{ev.lines}: {_fence_safe(ev.snippet)}", "```",
                  f"_{_fence_safe(ev.why)}_"]
    lines += ["", f"**Remediation:** {f.remediation.summary}", ""]
    return "\n".join(lines)


def render_markdown(
    manifest: DeltaManifest,
    fset: NormalizedFindingSet,
    verdict: str,
    triggers: list[Finding],
) -> str:
    verdict_txt = "🚩 **FLAGGED FOR REVIEW**" if verdict == "flagged" else "✅ **APPROVED**"
    s = manifest.stats
    by_sev = fset.counts.get("by_severity", {})
    sev_summary = " · ".join(f"{k}: {v}" for k, v in by_sev.items()) or "none"

    out = [
        f"# Security PR Review — {manifest.repo}#{manifest.pr_number}",
        "",
        f"**Verdict:** {verdict_txt}",
        "",
        f"- PR: {manifest.title or '(no title)'}"
        + (f" · by {manifest.author}" if manifest.author else ""),
        f"- Diff: {s.get('files', 0)} files, +{s.get('additions', 0)}/-{s.get('deletions', 0)}, "
        f"{s.get('hunks', 0)} hunks" + (" · ⚠️ oversize" if manifest.oversize else ""),
        f"- Findings: {fset.counts.get('total', 0)} ({sev_summary})",
        f"- Introduced by this PR: {fset.counts.get('introduced', 0)} · "
        f"pre-existing: {fset.counts.get('pre_existing', 0)}",
        f"- Gate triggers: {len(triggers)}",
        "",
        "---",
        "",
    ]
    # The two sets are separated rather than interleaved because they ask the
    # reviewer for different things (cross-cutting §5): one is this PR's to fix
    # before merge, the other is the repository's backlog and never blocks. A
    # single list makes the second kind read as this author's fault, which is
    # how a security tool loses its reader.
    introduced = [f for f in fset.findings if f.introduced_by_pr]
    pre_existing = [f for f in fset.findings if not f.introduced_by_pr]

    if not fset.findings:
        out.append("_No findings._")
    if introduced:
        out.append("## Findings introduced by this PR\n")
        out += [_finding_block(f) for f in introduced]
    if pre_existing:
        out.append("## Pre-existing findings (already present at the base commit)\n")
        out.append("_Reported for context. These do not affect the verdict._\n")
        out += [_finding_block(f) for f in pre_existing]

    out += [
        "---",
        "",
        "<sub>Generated by pr-review. Deterministic detectors only (M2): secrets, "
        "structural CPG rules, and any external scanners present. Agentic analysis "
        "and independent verification arrive at M3/M4, so every finding here is a "
        "candidate unless its detector produces direct evidence.</sub>",
    ]
    return "\n".join(out)
