"""Deterministic file classification (phase-0-extraction.md §3.3).

Path/extension-based in M0; content-marker heuristics (e.g. @generated headers)
arrive later. Drives the noise filter (Phase 2) and detector targeting.
"""
from __future__ import annotations

import re
from posixpath import basename

from pr_review.extract import deps

_LANG_BY_EXT = {
    ".py": "python", ".pyi": "python",
    ".js": "javascript", ".ts": "typescript",
    ".java": "java", ".go": "go", ".rb": "ruby",
}

_BINARY_EXT = {".png", ".jpg", ".jpeg", ".gif", ".pdf", ".zip", ".gz", ".whl",
               ".so", ".dylib", ".class", ".jar", ".ico", ".woff", ".woff2"}

# Derived, not restated (`OPEN_ITEMS.md` §5). `deps.py` is the single place that
# knows what a lockfile is called, because it is the module that parses them; a
# format added there is recognised here without anyone remembering to.
_LOCKFILES = deps.lockfile_names()
_DEP_MANIFESTS = deps.manifest_names()          # same derivation, same reason


def _ext(path: str) -> str:
    name = basename(path)
    return name[name.rfind("."):].lower() if "." in name else ""


def detect_lang(path: str) -> str | None:
    return _LANG_BY_EXT.get(_ext(path))


def is_test(path: str) -> bool:
    p = path.lower()
    name = basename(p)
    return (
        "/tests/" in f"/{p}" or p.startswith("tests/")
        or name.startswith("test_") or name.endswith("_test.py")
        or name == "conftest.py" or "/test/" in f"/{p}"
    )


# Header markers, per `plan/phase-0-extraction.md` §3. TWO independent signals are
# required, and that is the whole design -- see `is_generated`.
_GEN_MARKERS = ("is generated", "was generated", "auto-generated", "autogenerated",
                "@generated", "generated via", "generated file")
_EDIT_MARKERS = ("do not edit", "don't edit", "do not modify",
                 "changes will be overwritten")
_COMMENT_STARTS = ("#", "//", "/*", "*", "<!--", "--", ";", "!")
_HEADER_LINES = 10


def _has_generated_header(head: str) -> bool:
    """Both a "generated" phrase AND a "do not edit" phrase, in the first
    `_HEADER_LINES` **comment** lines.

    Every clause here was bought with a measurement (`BENCHMARK_STATUS.md` §4n).
    Over 305,861 files in the corpus trees:

      * any single marker, anywhere in the first 2 KB -- the shape
        `OPEN_ITEMS.md` §17 originally sketched -- newly suppresses **11,073
        files (3.6%)**, including `apply-templates.sh` and
        `generate-stackbrew-library.sh`: the hand-written scripts that DO the
        generating, whose text contains the header they emit.
      * requiring both signals in the first 10 comment lines newly suppresses
        **803 (0.26%)**, of which **640 are Dockerfiles** -- the intended target.

    So the two-signal rule is not conservatism for its own sake. One signal
    matches prose *about* generation; two matches a file that is announcing
    itself as output. `dependency-submission.yml` says "automatically generated"
    while describing GitHub's dependency graph, and stays visible under this
    rule; `self_schema.py` says "auto-generated by generate_self_schema.py, DO
    NOT edit" and does not.

    Comment-only matters for the same reason: it is what keeps a generator's own
    source, where these phrases appear as string literals, out of the set.
    """
    for line in head.splitlines()[:_HEADER_LINES]:
        stripped = line.strip()
        if not stripped.startswith(_COMMENT_STARTS):
            continue
        low = stripped.lower()
        if any(g in low for g in _GEN_MARKERS) and any(e in low for e in _EDIT_MARKERS):
            return True            # both on one line -- docker-library does this
    gen = edit = False
    for line in head.splitlines()[:_HEADER_LINES]:
        stripped = line.strip()
        if not stripped.startswith(_COMMENT_STARTS):
            continue
        low = stripped.lower()
        gen = gen or any(g in low for g in _GEN_MARKERS)
        edit = edit or any(e in low for e in _EDIT_MARKERS)
    return gen and edit


def is_generated(path: str, head: str | None = None) -> bool:
    """Build output and machine-written files.

    `head` is the first ~2 KB of the file when it is available, and `None` when
    it is not -- an offline run has a diff and no checkout (arm 2c), so the
    path-only answer has to stay correct on its own. Defaulting it keeps every
    existing caller working and makes the content half strictly additive.

    Consequential rather than cosmetic: `secrets.py` and `sast_semgrep.py` both
    skip a generated file outright, and `change/filter.py` drops it. So a false
    *negative* here is noise, and a false *positive* is silent lost coverage —
    which is why the list below stays close to what has actually been seen.

    Sourcemaps and `dist/` were added 2026-08-07 after the benchmark corpus
    produced a HIGH `SEC-PASSWORD` finding on
    `netbox/project-static/dist/netbox.js.map` — a minified sourcemap, matched
    on a base64 blob, with the whole 1.25 MB line captured as evidence. It was
    pre-existing on every case, so no scorecard ever showed it; the first sight
    of it was reading a run artifact by hand.

    `build/` is deliberately **not** here. It was not observed, and unlike
    `dist/` it routinely holds hand-written code (build scripts, tooling), so
    adding it would trade unmeasured coverage for a hypothetical — the same
    trade `python.yaml`'s single-segment patterns were spared in errata §14.22.
    """
    p = path.lower()
    name = basename(p)
    if (
        name.endswith("_pb2.py")
        or name.endswith(".min.js") or name.endswith(".min.css")
        # Sourcemaps: machine-written, and they embed the sources they map.
        or name.endswith(".js.map") or name.endswith(".css.map")
        or "/migrations/" in f"/{p}" or "/vendor/" in f"/{p}"
        or "/node_modules/" in f"/{p}" or "/.generated/" in f"/{p}"
        or "/dist/" in f"/{p}"
    ):
        return True
    return bool(head) and _has_generated_header(head)


def is_lockfile(path: str) -> bool:
    name = basename(path).lower()
    return name in _LOCKFILES or name.endswith(".lock")


def is_dep_manifest(path: str) -> bool:
    name = basename(path).lower()
    return name in _DEP_MANIFESTS or bool(re.match(r"requirements.*\.txt$", name))


def is_iac(path: str) -> bool:
    p = path.lower()
    name = basename(p)
    return (
        name.endswith(".tf") or name == "dockerfile" or name.startswith("dockerfile")
        or name.startswith("docker-compose") or "/k8s/" in f"/{p}" or "/helm/" in f"/{p}"
    )


def is_binary_ext(path: str) -> bool:
    return _ext(path) in _BINARY_EXT
